"""add_receipt_id_to_expenses

Revision ID: 034cdde7f636
Revises: 0e0c3bb49e06
Create Date: 2026-03-27 12:34:12.209872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034cdde7f636'
down_revision: Union[str, None] = '0e0c3bb49e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('receipt_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'receipts', ['receipt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'receipt_id')
    # ### end Alembic commands ###
