"""add_tax_discount_to_receipt_items

Revision ID: 0e0c3bb49e06
Revises: fe6911cce08a
Create Date: 2026-03-27 09:45:02.379366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0c3bb49e06'
down_revision: Union[str, None] = 'fe6911cce08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_items', sa.Column('is_taxable', sa.Boolean(), nullable=True))
    op.add_column('receipt_items', sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('receipt_items', sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_items', 'discount_amount')
    op.drop_column('receipt_items', 'tax_rate')
    op.drop_column('receipt_items', 'is_taxable')
    # ### end Alembic commands ###
